### ISSUE TITLE
Broken

### ISSUE THREAD

**Issue by GreenMan36** [fifty-six/zig.SteamManifestPatcher#1]
Both the original and this version is broken.
It stops after getting the process handle.

Quite sad since allot of people prefer using the Steam Console to downgrade.
I have a Steam Guide on Beat Saber that utilizes this.

**Comment by GreenMan36** [comment]
Thanks for the quick update but its still not quite fixed?

Here's the output:
```
Got process handle.
Module handle address: 5ad80000
error.PatternNotFound
Unable to dump stack trace: FileNotFound
Press ENTER to close.
```

**Comment by fifty-six** [comment]
What steam client version do you have? It seems to work with Steam package version 1608507519. Is your computer 32 or 64 bit?

**Comment by fifty-six** [comment]
Does [this](https://we.tl/t-rshay7Gdz4) work instead? If it doesn't, could you give me a copy of your steamclient.dll if you're sure that your steam is up-to-date

**Comment by GreenMan36** [comment]
Yo my bad, I've been getting a few messages but I guess all those dudes (including me) are on the Steam Beta branch.

Closing, thanks for the great work!
