### ISSUE TITLE
Trying to downpatch Elden Ring

### ISSUE THREAD

**Issue by BonjwaRedpanda** [fifty-six/zig.SteamManifestPatcher#12]
I'm trying to use the "SteamManifestPatcher" to downpatch Eldenring to a previous patch and download a depot. 

But everytime I open the .exe I get the following message:
Got process handle.
Module handle address: 51230000
error.PatternNotFound
Unable to dump stack trace: FileNotFound
Press ENTER to close.

I don't know what went wrong here.

**Comment by fifty-six** [comment]
I believe Steam should just allow downpatching at this point - they reactivated it semi-recently. I should probably archive this repo

**Comment by BonjwaRedpanda** [comment]
For Elden Ring it is not supported afaik - I was following this guide https://wiki.speedsouls.com/eldenring:Downpatching and it links to the ManifestPatcher. Thats why I was asking here directly.

**Comment by fifty-six** [comment]
Have you tried it? It was relatively recent - I can try it myself when I get home but it *should* work without running the patcher if you just run the `download_depot` command

**Comment by BonjwaRedpanda** [comment]
I tried the Download_depot and it intitially started in the console but never finished. Thats why i figured it must be because I'm not running the ManifestPatcher.

**Comment by BonjwaRedpanda** [comment]
I Tried again and will leave it running over night- thanks for the Quick answer:)

**Comment by fifty-six** [comment]
Yeah, it just takes a while with little to no feedback. If you look under the downloads tab in library it shows some network usage during it I believe. No problem!
