### ISSUE TITLE
FileNotFound error

### ISSUE THREAD

**Issue by kjhf** [fifty-six/zig.SteamManifestPatcher#2]
Hey, 
Running the v3 executable gives:

```
Got process handle.
error.UnableToEnumerate
Unable to dump stack trace: FileNotFound
Press ENTER to close.
```

Running Steam on Windows 10 (19042):
```
Built: May 18 2021
API: v020
Steam package versions: 1621394999
```

**Comment by fifty-six** [comment]
Is there any difference if you run it as administrator? UnableToEnumerate is from EnumProcessModulesEx failing.

**Comment by kjhf** [comment]
> Is there any difference if you run it as administrator? UnableToEnumerate is from EnumProcessModulesEx failing.

Yup that's the fix, thanks :)
