### ISSUE TITLE
Add Support for SteamCMD

### ISSUE THREAD

**Issue by rGunti** [fifty-six/zig.SteamManifestPatcher#4]
Hey,
I am the author of a small program called BeatSaberKeeper. The original intention of this program was to archive old versions of the VR game "Beat Saber" and to create backup copies of ones game states so in case of a forced update, a rollback would be easy. 

I had implemented SteamCMD as a downloader before the patch arrived and after that, my download feature became useless. I'd love to integrate this patch but as far as I understood your code (I have never seen Zig before) you're looking for a running process and patching it there. Would it be possible to extend it to also work with SteamCMD?

Thanks for your time and your work!

**Comment by nutterthanos** [comment]
> Hey,
> I am the author of a small program called BeatSaberKeeper. The original intention of this program was to archive old versions of the VR game "Beat Saber" and to create backup copies of ones game states so in case of a forced update, a rollback would be easy.
> 
> I had implemented SteamCMD as a downloader before the patch arrived and after that, my download feature became useless. I'd love to integrate this patch but as far as I understood your code (I have never seen Zig before) you're looking for a running process and patching it there. Would it be possible to extend it to also work with SteamCMD?
> 
> Thanks for your time and your work!

yeah the patch will work just need to change steam.exe in main.zig to steamcmd.exe and build it yourself

**Comment by fifty-six** [comment]
Yeah, that seems to work fine for me as well. I added an arg for it which I put up a new release with.

**Comment by rGunti** [comment]
That was quick! Great work, thanks!
