### ISSUE TITLE
Does this function on Linux?

### ISSUE THREAD

**Issue by Midnoclose** [fifty-six/zig.SteamManifestPatcher#8]
Regardless, please put the available platforms in the readme.

**Comment by fifty-six** [comment]
No, I don't have a linux version at the moment as this was mainly focused on people who would find the process of using DepotDownloader difficult and I thought that would be mainly windows users. I'd recommend [DepotDownloader](https://github.com/SteamRE/DepotDownloader) if you want to downpatch on linux. I'll put the platform in the README though, thanks for the reminder.
