### ISSUE TITLE
Integer Overflow

### ISSUE THREAD

**Issue by 1Poseidon3** [fifty-six/zig.SteamManifestPatcher#9]
Whenever I run this program, I get the following message in the console before it automatically closes

Got process handle.
Module handle address: 7b1d0000
68
Addr: 7b1d006a
thread 26896 panic: integer overflow
Unable to dump stack trace: FileNotFound

I can find no information on how to troubleshoot this error in any guide that references this software.

**Comment by d-rez** [comment]
Same issue here

![obraz](https://user-images.githubusercontent.com/1719659/146344409-d2a95067-9a99-4424-81b4-c3ffd99c7e85.png)

Steam version (Beta):

![obraz](https://user-images.githubusercontent.com/1719659/146344519-3a42dcbf-56ff-42cc-8fa9-f8219fad75bb.png)

EDIT: Rolling back to a stable non-Beta version of Steam did not help either
EDIT3: Downgrading executable to 3.1, 3.0 or v2 doesn't solve the issue on a stable Steam version

**Comment by fifty-six** [comment]
![image](https://user-images.githubusercontent.com/10470872/146450977-372acd30-13c4-4d01-ac43-cdc837657ca1.png)
I can't reproduce this on this stable, but it did happen to me on beta once? After going back from stable to beta it seems to be working fine again. 

![image](https://user-images.githubusercontent.com/10470872/146451436-d2f7a0e3-08e5-4adb-87bc-70be740de745.png)
Can you try the Dec 15 Steam build?

**Comment by 1Poseidon3** [comment]
I tried it with the Dec 16th Steam build and it worked all of a sudden. No idea what the issue was with the previous beta builds of Steam. Thanks.

**Comment by d-rez** [comment]
@fifty-six I think my Steam install was broken. It would not update to anything newer than Dec 14th and would not actually downgrade to anything once I signed out of Beta (would stay on Dec 14th build)

Had to nuke my whole Steam install and re-install. Now on Dec 16th version it worked fine lol

So weird. Thanks y'all

```Got process handle.
Module handle address: 78950000
68 10 C9 6E 79
Addr: 78d6e21d
Wrote patch to memory.
Press ENTER to close.
```
